# Generated by Django 3.2.6 on 2023-01-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('title_type', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('adult', models.BooleanField()),
                ('year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('birthday', models.CharField(max_length=10)),
                ('deathday', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('mid', models.CharField(max_length=256)),
                ('pid', models.CharField(max_length=256)),
                ('order', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('job', models.CharField(max_length=256)),
                ('chars', models.CharField(max_length=256)),
            ],
        ),
    ]
